### PR TITLE
Skip webgl2 extensions on webgl1

### LINKED ISSUE #461: webgl_generator fails to generate WebGL 1 bindings
using `Api::WebGl` instead of `Api::WebGl2` leads to compilation error:

    thread 'main' panicked at 'WebGLQuery'

### PR DESCRIPTION
**Pull request by Diggsey**
Fixes #461

### CODE REVIEW

File: webgl_generator/webgl_registry/mod.rs [hunk 1]
```diff
@@ -88,6 +92,11 @@ impl<'a> Exts<'a> {
                     convert_html_to_doc_comment(&overview_html)
                 ),
                 new_funs,
+                min_api: match api_dep.get_attribute("version", None).unwrap() {
+                    "1.0" => Api::WebGl,
+                    "2.0" => Api::WebGl2,
```
Comment (brendanzab) [inline webgl_generator/webgl_registry/mod.rs]: Hmm, I wonder if we should be smarter about parsing this... could break if a new version gets released. I guess we can fix it when it comes to that... 🤷‍♂️
